version: '2.1'

services:
  netdata:
    image: netdata/netdata
    hostname: ${HOSTNAME}.local # set to fqdn of host
    ports:
      - 9090:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
