version: '2.3'

services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped
    hostname: computin-PC.local # set to fqdn of host
    ports:
      - 9090:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
